# Generated by Django 3.0 on 2020-06-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('student', models.CharField(max_length=30)),
                ('professor', models.CharField(max_length=30)),
                ('grade', models.FloatField()),
                ('date', models.DateField()),
                ('observations', models.CharField(max_length=200)),
            ],
        ),
    ]
